apiVersion: apps/v1 
kind: Deployment
metadata:
  name: columbus-tonight-deployment
spec:
  selector:
    matchLabels:
      app: columbus-tonight
  replicas: 1
  template:
    metadata:
      labels:
        app: columbus-tonight
    spec:
      containers:
      - name: columbus-tonight
        image: ccarse.azurecr.io/columbus-tonight
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: myregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: columbus-tonight-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: columbus-tonight
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: columbus-tonight-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - columbus-tonight.com
    secretName: tls-secret
  rules:
  - host: columbus-tonight.com
    http:
      paths:
      - path: /
        backend:
          serviceName: columbus-tonight-service
          servicePort: 80